export const SELECT_SEARCH_TYPE = "SELECT_TYPE";

export const UNMOUNT_DEFAULT_SEARCH = "DELETE_ALL_SEARCH";

export const FETCH_DEFAULT_SEARCH = "GET_SEARCH";
export const FETCH_IMAGE = "GET_IMAGE";
